In [2]:
from pathlib import Path

import torch

from src.params import MODELS_DIR
from src.params import DatasetName, ModelName
from src.models import LogisticRegression

In [3]:
dataset_name = DatasetName.IMAGENET
model_name = ModelName.VITB8_DINO

weak_path = MODELS_DIR / f"{dataset_name.value}_{ModelName.ALEXNET.value}.pt"
st_gt_paths = list(MODELS_DIR.glob(f"{dataset_name.value}_{model_name.value}_*_stgt.pt"))
st_paths = list(MODELS_DIR.glob(f"{dataset_name.value}_{model_name.value}_*_st.pt"))


In [4]:
state_dict = torch.load(weak_path, weights_only=True, map_location="cpu")
state_dict

OrderedDict([('finetune.weight',
              tensor([[-0.0029, -0.0105, -0.0282,  ..., -0.0050,  0.0039, -0.0104],
                      [-0.0044, -0.0071, -0.0125,  ..., -0.0089, -0.0125, -0.0022],
                      [-0.0170, -0.0245, -0.0177,  ..., -0.0198, -0.0224, -0.0153],
                      ...,
                      [ 0.0012,  0.0091, -0.0051,  ..., -0.0121, -0.0225, -0.0019],
                      [-0.0113, -0.0213, -0.0222,  ..., -0.0119,  0.0048,  0.0022],
                      [-0.0117,  0.0037, -0.0068,  ..., -0.0094, -0.0135, -0.0053]])),
             ('finetune.bias',
              tensor([ 1.5061e-03,  6.7124e-03, -9.1438e-03,  6.4387e-03, -4.0912e-03,
                      -2.7495e-03, -4.7677e-03,  8.7348e-03,  1.8664e-04, -6.3728e-03,
                       2.1107e-04,  3.0890e-03,  8.2289e-03,  1.5757e-03, -2.6128e-04,
                       8.0203e-03,  8.5058e-03, -4.7903e-03,  7.7292e-03, -1.0597e-02,
                       3.1658e-03, -1.1980e-03,  7.405

In [3]:
st_gt_path = st_gt_paths[0]
state_dict = torch.load(st_gt_path, weights_only=True, map_location="cpu")
state_dict

OrderedDict([('finetune.weight',
              tensor([[ 0.0018, -0.0321,  0.0306,  ..., -0.0009,  0.0131, -0.0200],
                      [-0.0166, -0.0198, -0.0065,  ...,  0.0086,  0.0134,  0.0242],
                      [-0.0118,  0.0222, -0.0045,  ...,  0.0066, -0.0235,  0.0326],
                      ...,
                      [ 0.0105,  0.0246, -0.0005,  ...,  0.0126,  0.0112,  0.0332],
                      [ 0.0202, -0.0212, -0.0154,  ...,  0.0305, -0.0265, -0.0090],
                      [-0.0233,  0.0202,  0.0142,  ...,  0.0045, -0.0119,  0.0266]])),
             ('finetune.bias',
              tensor([-3.0251e-02, -1.4475e-02,  2.2439e-02, -2.5356e-02,  6.5823e-03,
                      -3.0999e-02,  1.7428e-02, -2.8588e-02,  3.0291e-02,  2.1036e-02,
                       1.9565e-03, -2.9574e-02, -1.6084e-02, -1.1282e-02, -2.7878e-02,
                      -1.2884e-02, -8.7619e-03, -1.0581e-02, -1.1371e-02, -1.3764e-02,
                       1.8055e-02,  2.9886e-02, -1.591