In [1]:
import torch
import torch.nn.functional as F
import torchvision.transforms as T

from src.params import DatasetName, CPU, CPU_GENERATOR
from src.datasets import load_dataset


dataset_name = DatasetName.MNIST

transform = T.Compose([T.ToTensor(), T.Lambda(lambda x: torch.flatten(x)), T.Lambda(lambda x: (x - x.mean()) / x.std()),])
num_classes = 10
target_transform = lambda x: F.one_hot(torch.tensor(x), num_classes=10).to(torch.float32)

train_dataset = load_dataset(dataset_name, split="train", transform=transform, target_transform=target_transform)



In [5]:
inds = torch.randint(
    len(train_dataset),
    size=(10,),
    device=CPU,
    generator=CPU_GENERATOR,
)

for i in range(10):
    print(len(train_dataset[inds[i]]))

2
2
2
2
2
2
2
2
2
2


In [1]:
import torch
from src.torch_utils import project_to_simplex

a = torch.tensor([[0.1, 0.2, 0.3, 0.4]])
print(project_to_simplex(a, dim=1))

b = torch.tensor([[0.1, 0.2, 0.3, 0.4, 0.5]])
print(project_to_simplex(b, dim=1))

c = -a
print(project_to_simplex(c, dim=0))

tensor([[0.1000, 0.2000, 0.3000, 0.4000]])
tensor([[7.4506e-09, 1.0000e-01, 2.0000e-01, 3.0000e-01, 4.0000e-01]])
tensor([[1.0000, 1.0000, 1.0000, 1.0000]])


In [15]:
import torch

a = torch.randn((3,4,2), dtype=torch.float32)
print(a)

select_values = torch.argmax(a, dim=1)
print(select_values.shape)
print(select_values)

# b = a[torch.arange(a.shape[0])[:, None], select_values, torch.arange(a.shape[2])[None, :]]
# print(b.shape)
# print(b)
b = torch.gather(a, 1, select_values[:, None, :])
print(b.shape)
print(b)

tensor([[[ 1.1992,  0.4377],
         [ 0.7124,  1.2945],
         [-0.5586,  1.0156],
         [-2.3449,  0.5986]],

        [[ 0.7308, -1.5321],
         [ 0.6309,  0.2212],
         [ 0.6564, -0.4714],
         [-1.4044, -0.7132]],

        [[ 0.7181, -1.9816],
         [ 0.8546,  0.0317],
         [-0.2629, -2.2367],
         [-0.0189,  0.2391]]])
torch.Size([3, 2])
tensor([[0, 1],
        [0, 1],
        [1, 3]])
torch.Size([3, 1, 2])
tensor([[[1.1992, 1.2945]],

        [[0.7308, 0.2212]],

        [[0.8546, 0.2391]]])


In [1]:
import torch
from src.torch_utils import hardmax

a = torch.randn((3,4), dtype=torch.float32)
print(a)

print(hardmax(a, dim=1))

tensor([[ 1.4174,  0.9557, -0.1949, -0.3789],
        [ 0.2731, -1.1324,  0.5466,  1.3071],
        [-1.3661,  1.5791,  0.6180,  1.6229]])
tensor([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])


In [6]:
import torch

a = torch.randn((3,4), dtype=torch.float32)
print(a)

print(torch.softmax(a, dim=1))
print(torch.softmax(a[0], dim=0))

tensor([[-0.2152, -1.2088, -0.1387, -3.4092],
        [-0.7293, -0.9411, -0.4702,  1.9118],
        [-0.6716, -0.4142,  1.3076, -2.4740]])
tensor([[0.4015, 0.1486, 0.4334, 0.0165],
        [0.0584, 0.0472, 0.0756, 0.8188],
        [0.1031, 0.1334, 0.7464, 0.0170]])
tensor([0.4015, 0.1486, 0.4334, 0.0165])


In [2]:
import torch

OUT_DIM = 1
test_points = []
for dim in range(OUT_DIM):
    test_points.append(torch.linspace(-1, 1, 3))
test_points = torch.stack(torch.meshgrid(*test_points), dim=-1).reshape(-1, OUT_DIM)
print(test_points)

tensor([[-1.],
        [ 0.],
        [ 1.]])


In [1]:
import torch

dev = torch.device("cpu")
type(dev)
torch.cuda.is_available()

True

In [4]:
import torch

torch.randn(1, requires_grad=True)[0]

tensor(-0.7976, grad_fn=<SelectBackward0>)

In [3]:
import torch

a = torch.randn(5, 2)
print(a)
torch.diag_embed(a)

tensor([[-0.2363, -1.3349],
        [-0.4418, -0.4420],
        [-1.5690,  0.7368],
        [ 2.5167,  0.5386],
        [-0.6326,  0.3073]])


tensor([[[-0.2363,  0.0000],
         [ 0.0000, -1.3349]],

        [[-0.4418,  0.0000],
         [ 0.0000, -0.4420]],

        [[-1.5690,  0.0000],
         [ 0.0000,  0.7368]],

        [[ 2.5167,  0.0000],
         [ 0.0000,  0.5386]],

        [[-0.6326,  0.0000],
         [ 0.0000,  0.3073]]])

In [10]:
from src.models import MLP

model = MLP(10, 10, 5, 2)
next(model.parameters()).device

device(type='cpu')

In [1]:
import torch

from src.models import load_model
from src.params import ModelName, DeviceType

import os

os.environ["TORCH_HOME"] = "../../pythagoras-agi/.cache"

model = load_model(ModelName.ALEXNET, device=torch.device(DeviceType.CPU.value))

/home/abhmul/miniforge3/envs/pagi/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/abhmul/miniforge3/envs/pagi/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [2]:
import torch.utils.data as data

from src.datasets import load_dataset
from src.params import DatasetName

dataset = load_dataset(DatasetName.CIFAR10)

data_loader = data.DataLoader(dataset, batch_size=32, shuffle=True)

for start, (x,y) in zip(range(5), data_loader):
    print("===========")
    print(type(x))
    print(x.shape)
    out = model(x)
    print(out)
    print(out.shape)
    print(type(y))
    print(y.shape)



Files already downloaded and verified
<class 'torch.Tensor'>
torch.Size([32, 3, 224, 224])
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.8587, 1.7643, 0.8499],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [2.4350, 3.0836, 2.7548,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       grad_fn=<ViewBackward0>)
torch.Size([32, 9216])
<class 'torch.Tensor'>
torch.Size([32])
<class 'torch.Tensor'>
torch.Size([32, 3, 224, 224])
tensor([[0.0000, 0.4306, 0.5704,  ..., 0.9128, 0.9128, 0.0000],
        [1.2582, 1.2582, 0.5419,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.7013, 2.0164,  ..., 0.0000, 0.0000, 1.1655],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.4083, 0.0236,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.000

In [1]:
from src.params import ModelName, DatasetName
from src.datasets import load_embeddings

alex = load_embeddings(DatasetName.CIFAR10, ModelName.ALEXNET)
alex_y_tr = alex.y_train
alex_y_te = alex.y_test
alex = None

resnet = load_embeddings(DatasetName.CIFAR10, ModelName.RESNET50_DINO)
resnet_y_tr = resnet.y_train
resnet_y_te = resnet.y_test
resnet = None

vitb = load_embeddings(DatasetName.CIFAR10, ModelName.VITB8_DINO)
vitb_y_tr = vitb.y_train
vitb_y_te = vitb.y_test
vitb = None



In [2]:
assert (alex_y_tr == resnet_y_tr).all()
assert (alex_y_tr == vitb_y_tr).all()
assert (alex_y_te == resnet_y_te).all()
assert (alex_y_te == vitb_y_te).all()


In [1]:
from src.models import get_alexnet_classifier, alexnet

alex = alexnet()
alex_classifier = get_alexnet_classifier()

alex_classifier

/home/abhmul/miniforge3/envs/pagi/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/abhmul/miniforge3/envs/pagi/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Sequential(
  (0): Dropout(p=0.5, inplace=False)
  (1): Linear(in_features=9216, out_features=4096, bias=True)
  (2): ReLU(inplace=True)
  (3): Dropout(p=0.5, inplace=False)
  (4): Linear(in_features=4096, out_features=4096, bias=True)
  (5): ReLU(inplace=True)
  (6): Linear(in_features=4096, out_features=1000, bias=True)
)